#riot-web-debug:
#  only:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /\[DEBUG\]/
#  script:
#    - curl -X POST -F "token=$UPDATE_TOKEN" -F ref=master -F "variables[RIOTDEVELOP]=true" -F "variables[DEBUG]=true" -F "variables[RIOT]=true" http://192.168.1.18/api/v4/projects/28/trigger/pipeline

#riot-web-develop:
#  except:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /\[RELEASE\]/
#      - $CI_COMMIT_MESSAGE =~ /\[DEBUG\]/
#  script:
#    - curl -X POST -F "token=$UPDATE_TOKEN" -F ref=master -F "variables[RIOTDEVELOP]=true" -F "variables[DEBUG]=false" -F "variables[RIOT]=true" http://192.168.1.18/api/v4/projects/28/trigger/pipeline

#riot-web-release:
#  only:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /\[RELEASE\]/
#  script:
#    - curl -X POST -F "token=$UPDATE_TOKEN" -F ref=master -F "variables[RIOTRELEASE]=true" -F "variables[DEBUG]=false" -F "variables[RIOT]=true" http://192.168.1.18/api/v4/projects/28/trigger/pipeline
